#!/usr/bin/env python
import rospy
from visualization_msgs.msg import Marker
from time import sleep

rospy.init_node('obstacle2rviz')
sleep(0.5)

pub = rospy.Publisher('/obstacle_marker', Marker, queue_size=1, latch=True)

msg = Marker()
msg.action = Marker.ADD
# msg.action = Marker.DELETEALL
msg.type = Marker.MESH_RESOURCE
msg.mesh_resource = 'package://stack_of_task_space_controllers_kuka_lwr/resources/obstacle.dae'
msg.header.frame_id = 'world'
msg.pose.orientation.w = 0.70738827
msg.pose.orientation.y = 0.
msg.pose.orientation.x = 0.
msg.pose.orientation.z = 0.70682518
msg.pose.position.x = -0.2
msg.pose.position.y = -0.05
msg.scale.x = msg.scale.y = msg.scale.z = 1.0
msg.color.a = .8
msg.color.b = 1.0

pub.publish(msg)
sleep(0.5)
