#!/usr/bin/env python

import pyexotica as exo
from numpy import array
import math
from pyexotica.publish_trajectory import *
from std_msgs.msg import Float64MultiArray
import rospy
from time import sleep, time
import signal

rospy.init_node("figure_eight_ik")

def figure_eight(t):
    return array([0.6, -0.1 + math.sin(t * 2.0 * math.pi * 0.5) * 0.1, 0.5 + math.sin(t * math.pi * 0.5) * 0.2, 0, 0, 0])


exo.Setup.init_ros()
solver = exo.Setup.load_solver(
    '{stack_of_passive_controllers_controller}/config/figure_eight_ik.xml')
problem = solver.get_problem()

pub = rospy.Publisher("/lwr/lwr_control/command", Float64MultiArray, queue_size=1)

dt = 0.01
t = 0.0
q = array([0.0] * 14)
print('Publishing IK')
signal.signal(signal.SIGINT, sig_int_handler)
while True:
    try:
        problem.set_goal('Position', figure_eight(t))
        problem.start_state = q
        s = time()
        q = solver.solve()[0]
        publish_pose(q, problem)
        msg = Float64MultiArray()
        msg.data = q[:7]
        pub.publish(msg)
        e = time()
        if e - s < dt:
            sleep(dt - (e-s))
        t = t + dt
    except KeyboardInterrupt:
        break
