name: ROS-CI
on: [push, pull_request]

jobs:
  CI:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic, CLANG_FORMAT_CHECK: file, CLANG_FORMAT_VERSION: "6.0"}
          - {ROS_DISTRO: noetic}
    env:
      UPSTREAM_WORKSPACE: dependencies.rosinstall
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
